learning to work
Alexei66/Files pull request #2
Opened 2023-02-07 23:45 UTC by Alexei66

1. Изменил метод с лишним присвоением в string
2. Добавил проверку для пустого файла

2023-02-07 23:49 UTC, den4ik124 requested changes

2023-02-07 23:49 UTC, den4ik124 commented on Program.cs
> +            if (empty == true)
Почему бы сразу в if не втулитб метод IsNullOrEmpty?)

И зачем опять сравниваешь bool и bool внутри if ?

2023-02-07 23:51 UTC, den4ik124 commented
Договаривались сделать Main максимально пустым)

2023-02-12 11:20 UTC, den4ik124 requested changes

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +
поставь расширение CodeMaid чтобы оно за тебя чистило лишние строки, пробелы и форматировало код более менее)

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +                 string compressed = @"E:\�#\SB\Date\res_txt.7z"; // ���� ���� ��������� �����
я, вот, склонировал твой код... запустил, а оно не работает)
Подумай почему и как такое можно исправить, чтобы работало у всех, кто на Windows запустит код

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +
так же лишние строки

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +                    return;
Я не уверен, что этот return отработает правильно и закончит метод Start в случае невалидного значения в строке.
Если хочешь использовать метод для проверки - возвращай bool и в методе Start уже проверяй, что там со строкой... валидная или нет... если не валидная - return из метода Start

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +                 int N = int.Parse(numbN);
желательно давать более осмысленные имена переменным... что такое N - хз)

+ форматирование поплыло
Попробуй CTRL+K, D жмякать

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +                    TimeSpan timeSpan = DateTime.Now.Subtract(date);  // ����������� ������� �� �������
Не самый лучший вариант замера времени выполнения.
Почитай про Stopwatch и как его использовать

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +                    }
Это напрашивается в отдельный метод, т.к. запись в файл - это одно... а создать архив - это уже другое...

2023-02-12 11:20 UTC, den4ik124 commented on App.cs
> +                    TimeSpan timeSpan = DateTime.Now.Subtract(date);
опять же... читай про Stopwatch

2023-02-12 12:15 UTC, Alexei66 commented on App.cs
> +
установил расширение

2023-02-12 12:23 UTC, Alexei66 commented on App.cs
> +                 int N = int.Parse(numbN);
заменил N на numberFromFile

2023-02-12 13:26 UTC, den4ik124 requested changes

2023-02-12 13:26 UTC, den4ik124 commented on Program.cs
> +        //}
Комменты не нужны в ПР. Если код закомментирован - он не нужен

2023-02-15 18:10 UTC, closed without merging